[package]
name = "func-minimization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
term-table = "1.3.2"
term_size = "0.3.2"
termcolor = "1.2.0"
